
package ku.astro.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AstronomicalUnitSoap", targetNamespace = "http://www.webserviceX.NET/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AstronomicalUnitSoap {


    /**
     * 
     * @param astronomicalValue
     * @param fromAstronomicalUnit
     * @param toAstronomicalUnit
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ChangeAstronomicalUnit", action = "http://www.webserviceX.NET/ChangeAstronomicalUnit")
    @WebResult(name = "ChangeAstronomicalUnitResult", targetNamespace = "http://www.webserviceX.NET/")
    @RequestWrapper(localName = "ChangeAstronomicalUnit", targetNamespace = "http://www.webserviceX.NET/", className = "net.webservicex.ChangeAstronomicalUnit")
    @ResponseWrapper(localName = "ChangeAstronomicalUnitResponse", targetNamespace = "http://www.webserviceX.NET/", className = "net.webservicex.ChangeAstronomicalUnitResponse")
    public double changeAstronomicalUnit(
        @WebParam(name = "AstronomicalValue", targetNamespace = "http://www.webserviceX.NET/")
        double astronomicalValue,
        @WebParam(name = "fromAstronomicalUnit", targetNamespace = "http://www.webserviceX.NET/")
        Astronomicals fromAstronomicalUnit,
        @WebParam(name = "toAstronomicalUnit", targetNamespace = "http://www.webserviceX.NET/")
        Astronomicals toAstronomicalUnit);

}
